# numpy

In [5]:
import numpy as np


In [9]:
sarasas = [5, 1, 3, 7, 6]
vektorius = np.array(sarasas)
print(vektorius)

[5 1 3 7 6]


In [11]:
sarasai = [
    [4, 5, 6],
    [1, 2, 3], 
    [7, 8, 9]
]
matrica = np.matrix(sarasai)
print(matrica)

[[4 5 6]
 [1 2 3]
 [7 8 9]]


In [15]:
np.arange(0, 78, 7)

array([ 0,  7, 14, 21, 28, 35, 42, 49, 56, 63, 70, 77])

In [18]:
print(np.zeros(7))

[0. 0. 0. 0. 0. 0. 0.]


In [29]:
print(np.zeros((7, 7), dtype=int))

[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]


In [36]:
print(np.linspace(0, 20, 5))

[ 0.  5. 10. 15. 20.]


In [43]:
vienetine = np.eye(7, dtype=int)
vienetine[3,4] = 5
print(vienetine)

[[1 0 0 0 0 0 0]
 [0 1 0 0 0 0 0]
 [0 0 1 0 0 0 0]
 [0 0 0 1 5 0 0]
 [0 0 0 0 1 0 0]
 [0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1]]


# random array/matricos

In [46]:
np.random.rand(10)

array([0.48869265, 0.64579509, 0.92818526, 0.23786825, 0.02614187,
       0.33811044, 0.95557791, 0.15632094, 0.11393486, 0.33267459])

In [51]:
print(np.random.rand(3, 3))

[[0.65584406 0.54517184 0.83930666]
 [0.62378472 0.22302825 0.5126118 ]
 [0.85433087 0.15442824 0.96270159]]


In [54]:
print(np.random.randn(3, 3))

[[ 0.39699107  1.19120132  2.27922555]
 [ 0.52243496  1.14807552 -1.30580444]
 [-0.10024406 -0.26752185 -0.82590096]]


In [60]:
print(np.random.randint(-9, 10, 77))

[-1  1  4 -7  1  4  6 -3 -9  3 -6  1  2  2 -6 -8 -4 -4 -7  1  9  0 -8 -3
 -9  1  0 -9  3 -4 -5 -2  2  3 -9  3  9 -8  0  2 -9 -3  1  3  9  1 -3  9
  4 -9 -1 -5 -3 -8  3 -6  7 -9 -6 -1 -7 -5  7  0 -6  7 -2  1  4  5 -2  7
 -3  3 -4 -6  6]


# masyvų pertvarkymas

In [81]:
masyvas = np.random.randint(-99, 100, 40)
pertvarkyta = masyvas.reshape(5, 8)
print(pertvarkyta)

[[ 36 -47 -36 -21 -78  39 -90 -95]
 [ -2  76 -79  77  -6   8  98  21]
 [-73 -45 -87  20 -87 -50 -44  71]
 [ 34 -80  21  31 -30  37 -78  83]
 [ 30  -2 -94 -27 -67  62  49  96]]


In [82]:
print(pertvarkyta.min())
print(pertvarkyta.max())

-95
98


In [83]:
print(pertvarkyta.argmin())
print(pertvarkyta.argmax())

7
14


In [85]:
print(pertvarkyta.shape)
print(pertvarkyta.dtype)

(5, 8)
int64


In [91]:
len(str(2**64))

20

# indeksacija ir reikšmių traukimas

In [93]:
masyvas[5]

39

In [96]:
masyvas[3:13]

array([-21, -78,  39, -90, -95,  -2,  76, -79,  77,  -6])

In [102]:
masyvas[::4] = 44
masyvas[7] = 77
masyvas[21] = -42

In [103]:
masyvas.reshape(4, 10)

array([[ 44, -47, -36, -21,  44,  39, -90,  77,  44,  76],
       [-79,  77,  44,   8,  98,  21,  44, -45, -87,  20],
       [ 44, -42, -44,  71,  44, -80,  21,  31,  44,  37],
       [-78,  83,  44,  -2, -94, -27,  44,  62,  49,  96]])

In [98]:
pertvarkyta[0, 0]

36

In [105]:
pertvarkyta[1:4, 5:8]

array([[  8,  98,  21],
       [-42, -44,  71],
       [ 37, -78,  83]])

In [139]:
masyvas = np.random.randint(0, 100, 100)
matrica = masyvas.reshape(10, 10)
matrica

array([[87, 30,  2, 31, 46, 93,  0, 23, 38, 50],
       [45, 88, 38, 59, 87, 50, 87, 70, 34, 61],
       [10, 30, 68, 73, 99, 68, 97, 60, 98, 36],
       [25, 38, 80, 66, 48, 84, 74, 52, 18, 76],
       [ 0, 76, 90, 96, 49,  0, 55, 26,  3, 57],
       [15, 77, 43, 53, 18, 76, 49, 36, 52, 51],
       [95, 81, 61, 70, 12, 79, 13, 39, 43, 42],
       [ 7,  2, 75, 62, 86, 59, 16, 24, 27, 65],
       [29, 11, 87, 18, 33, 35, 68, 40, 98, 65],
       [44, 14, 62, 23, 39,  6, 28,  3,  8, 51]])

In [108]:
matrica[::2, ::2]

array([[11, 72, 42, 81, 62],
       [86, 94, 95, 64, 57],
       [27, 22, 32,  5, 78],
       [ 8, 32,  6, 64,  0],
       [91, 80, 20, 37, 86]])

In [112]:
matrica[-2::-2, -2::-2]

array([[86, 37, 20, 80, 91],
       [ 0, 64,  6, 32,  8],
       [78,  5, 32, 22, 27],
       [57, 64, 95, 94, 86],
       [62, 81, 42, 72, 11]])

In [118]:
matrica[:, 0:2]

array([[11, 93],
       [51, 47],
       [86, 86],
       [35, 78],
       [27,  2],
       [46, 18],
       [ 8, 78],
       [92, 16],
       [91, 19],
       [19, 89]])

# traukimas pagal sąlygą

In [122]:
masyvas

array([11, 93, 72,  8, 42, 13, 81, 61, 62, 21, 51, 47, 30, 65,  3, 32, 86,
       81, 67, 84, 86, 86, 94, 64, 95, 43, 64, 53, 57, 82, 35, 78, 38, 97,
       68, 92, 20, 49, 16, 93, 27,  2, 22, 37, 32, 54,  5, 38, 78, 90, 46,
       18, 96, 62, 69, 57, 73,  3, 96, 85,  8, 78, 32, 92,  6, 13, 64, 78,
        0, 96, 92, 16, 72, 61, 62, 88, 75, 77, 18, 93, 91, 19, 80, 19, 20,
        2, 37, 96, 86, 79, 19, 89, 16, 14, 31,  2,  8, 46, 82, 35])

In [123]:
masyvas > 30

array([False,  True,  True, False,  True, False,  True,  True,  True,
       False,  True,  True, False,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
       False,  True, False,  True, False, False, False,  True,  True,
        True, False,  True,  True,  True,  True, False,  True,  True,
        True,  True,  True, False,  True,  True, False,  True,  True,
        True, False, False,  True,  True, False,  True,  True, False,
        True,  True,  True,  True,  True,  True, False,  True,  True,
       False,  True, False, False, False,  True,  True,  True,  True,
       False,  True, False, False,  True, False, False,  True,  True,
        True])

In [121]:
masyvas[masyvas > 30]

array([93, 72, 42, 81, 61, 62, 51, 47, 65, 32, 86, 81, 67, 84, 86, 86, 94,
       64, 95, 43, 64, 53, 57, 82, 35, 78, 38, 97, 68, 92, 49, 93, 37, 32,
       54, 38, 78, 90, 46, 96, 62, 69, 57, 73, 96, 85, 78, 32, 92, 64, 78,
       96, 92, 72, 61, 62, 88, 75, 77, 93, 91, 80, 37, 96, 86, 79, 89, 31,
       46, 82, 35])

In [124]:
iki_30 = masyvas < 30
print(iki_30)

[ True False False  True False  True False False False  True False False
 False False  True False False False False False False False False False
 False False False False False False False False False False False False
  True False  True False  True  True  True False False False  True False
 False False False  True False False False False False  True False False
  True False False False  True  True False False  True False False  True
 False False False False False False  True False False  True False  True
  True  True False False False False  True False  True  True False  True
  True False False False]


In [125]:
masyvas[iki_30]

array([11,  8, 13, 21,  3, 20, 16, 27,  2, 22,  5, 18,  3,  8,  6, 13,  0,
       16, 18, 19, 19, 20,  2, 19, 16, 14,  2,  8])

In [126]:
masyvas[iki_30] = 30
masyvas

array([30, 93, 72, 30, 42, 30, 81, 61, 62, 30, 51, 47, 30, 65, 30, 32, 86,
       81, 67, 84, 86, 86, 94, 64, 95, 43, 64, 53, 57, 82, 35, 78, 38, 97,
       68, 92, 30, 49, 30, 93, 30, 30, 30, 37, 32, 54, 30, 38, 78, 90, 46,
       30, 96, 62, 69, 57, 73, 30, 96, 85, 30, 78, 32, 92, 30, 30, 64, 78,
       30, 96, 92, 30, 72, 61, 62, 88, 75, 77, 30, 93, 91, 30, 80, 30, 30,
       30, 37, 96, 86, 79, 30, 89, 30, 30, 31, 30, 30, 46, 82, 35])

In [133]:
naujas = np.random.randint(0, 100, 20)
naujas[naujas > 50] = np.random.randint(0, 100)
naujas

array([34, 67, 67, 67,  0, 27, 67, 67,  0,  0, 67, 67, 43, 28, 23, 37, 28,
       67,  2, 32])

In [145]:
kopija = masyvas.copy()
ispjova = kopija[30:60]
ispjova[:] = 99
print(masyvas)
print(kopija)
print(ispjova)

[87 30  2 31 46 93  0 23 38 50 45 88 38 59 87 50 87 70 34 61 10 30 68 73
 99 68 97 60 98 36 25 38 80 66 48 84 74 52 18 76  0 76 90 96 49  0 55 26
  3 57 15 77 43 53 18 76 49 36 52 51 95 81 61 70 12 79 13 39 43 42  7  2
 75 62 86 59 16 24 27 65 29 11 87 18 33 35 68 40 98 65 44 14 62 23 39  6
 28  3  8 51]
[87 30  2 31 46 93  0 23 38 50 45 88 38 59 87 50 87 70 34 61 10 30 68 73
 99 68 97 60 98 36 99 99 99 99 99 99 99 99 99 99 99 99 99 99 99 99 99 99
 99 99 99 99 99 99 99 99 99 99 99 99 95 81 61 70 12 79 13 39 43 42  7  2
 75 62 86 59 16 24 27 65 29 11 87 18 33 35 68 40 98 65 44 14 62 23 39  6
 28  3  8 51]
[99 99 99 99 99 99 99 99 99 99 99 99 99 99 99 99 99 99 99 99 99 99 99 99
 99 99 99 99 99 99]


In [142]:
masyvas.copy() == masyvas

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [153]:
tarpinis = masyvas[masyvas >= 30]
tarpinis[tarpinis < 60]

array([30, 31, 46, 38, 50, 45, 38, 59, 50, 34, 30, 36, 38, 48, 52, 49, 55,
       57, 43, 53, 49, 36, 52, 51, 39, 43, 42, 59, 33, 35, 40, 44, 39, 51])

# matematinės operacijos

In [155]:
vektorius = np.arange(1, 11, 1)
vektorius

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [159]:
vektorius ** 3

array([   1,    8,   27,   64,  125,  216,  343,  512,  729, 1000])

In [164]:
vektorius ** 3 / vektorius

array([  1.,   4.,   9.,  16.,  25.,  36.,  49.,  64.,  81., 100.])

In [165]:
vektorius / 0

/tmp/ipykernel_10035/17242066.py:1: RuntimeWarning: divide by zero encountered in divide
  vektorius / 0


array([inf, inf, inf, inf, inf, inf, inf, inf, inf, inf])

In [167]:
(vektorius + 100) / 10

array([10.1, 10.2, 10.3, 10.4, 10.5, 10.6, 10.7, 10.8, 10.9, 11. ])

In [168]:
np.sin(vektorius)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111])

In [169]:
np.tan(vektorius)

array([ 1.55740772, -2.18503986, -0.14254654,  1.15782128, -3.38051501,
       -0.29100619,  0.87144798, -6.79971146, -0.45231566,  0.64836083])

In [171]:
vektorius ** 2

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [170]:
np.log(vektorius ** 2)

array([0.        , 1.38629436, 2.19722458, 2.77258872, 3.21887582,
       3.58351894, 3.8918203 , 4.15888308, 4.39444915, 4.60517019])